### ISSUE TITLE
[#1501] Implementar deploy automático nas branches acordadas

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-documentation#10]
## Sobre a Tarefa

Procurar ferramentas gratuitas para deploy automático e aplicar nas branches acordadas (sugestão de ferramentas: Vercel, Render, Cloudify e planos gratuitos da Google Cloud, AWS e Azure)

~~Heroku~~

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Utilizar ferramentas gratuitas

**Comment by ThHenrique** [comment]
[Render_Service (1).pdf](https://github.com/The-Bugger-Ducks/cloud-fox-documentation/files/9567633/Render_Service.1.pdf)
