### ISSUE TITLE
[#0306] Realizar modelagem dos sensores novamente

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-documentation#14]
## Sobre a Tarefa

Realizar a modelagem das tabelas Sensores e Parametros lavando em consideração os comentários dados pelo cliente
(Evitar a repetição de dados no datalogger e flexibilidade dos parametros)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
~~Detalhes de acesso (que perfil pode acessar o que nesta tarefa)~~
~~Endpoints a serem utilizadas~~
~~Protótipo~~

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] O banco tem que ser flexivel a novos tipos de parametros exemplo: Pluviometro de 25mm e Pluviometro de 50mm

**Comment by ThHenrique** [comment]
@GabrielCamargoL consegue anexar a modelagem ? pode ser um print simples do whimsical

**Comment by GabrielCamargoL** [comment]
@ThHenrique print da pasta doc do projeto: db.drawio, ou quer uma versão do whimsical?

![image](https://user-images.githubusercontent.com/55204419/194416004-0344d08d-8bb2-4710-93ce-6715ecc11e69.png)

**Comment by ThHenrique** [comment]
é isso mesmo que eu queria
