### ISSUE TITLE
DoR, DoD, templates de US, requisitos e tasks

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-documentation#3]
## Sobre a Tarefa

Descrição da tarefa

### User Story

Definition of Ready - User Story

- [ ] Critérios de aceitação
- [ ] Estimativa da equipe (Story Points)
- [ ] Conhecimento de todos sobre a US
- [ ] Busca aplicar o Modelo de INVEST (Independent, Negotiable, Valuable, Estimate, Small, Testable)
- [ ] Documentada no kanban e readme
- [ ] Segue o formato de voz do usuário: QUEM , O QUE, POR QUE
- [ ] Wireframe de baixa findelidade (caso task design/front-end)

Definition of Done - User Story
- [ ] Atende aos critérios de aceitação
- [ ] Testado e integrado
- [ ] Validado (por ex.: designs) / mostrado para as partes interessadas
- [ ] Sem bugs observados / review
- [ ] Documentado
- [ ] Aceito pelo PO

#### Definition of Ready
- [ ] Critério de aceite
- [ ] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [ ] Endpoints a serem utilizadas
- [ ] Protótipo

#### Definition of Done
- [ ] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Code review
- [ ] Atende aos critérios de aceite
- [ ] Documentado
- [ ] Aceito pelo PO

#### Critérios de aceitação: 
- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

**Comment by MariaGabrielaReis** [comment]
## Sobre a Tarefa

Configurar banco de dados, criando as tabelas necessárias para armazenar os dados dos usuários

> Detalhes de acesso (que perfil pode o que):
> Layout: [link do Figma]()

---
### Definition of Done
- [ ] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by ThHenrique** [comment]
@MariaGabrielaReis adicionei modelo de DoR, DoD e Critério de aceite. Estou esquecendo de algo ?

**Comment by MariaGabrielaReis** [comment]
Nope, tá belezinha, ó, grandioso PO 💯 

amanhã a gente organiza as infos das USs pra colocar no readme e essa questão mais grossa da documentação fica mais tranquila, obrigada pelo seu trabalho duro!
