### ISSUE TITLE
[#1701] Definição do fluxo de branches e sua criação

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-documentation#9]
## Sobre a Tarefa

Descrever os tipos de branch que irão existir no projeto, bem como as motivações de cada um

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)

#### Definition of Done
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Utilizar as convenções adotadas pelo mercado (git flow, ex)

**Comment by MariaGabrielaReis** [comment]
## Branches e suas motivações

- **main**: branch principal, com o código na versão de produção. Onde todas as funcionalidades são desenvolvidas em outras branches e depois mescladas a main
- **develop**: branch dos códigos do próximo deploy, onde hão todas as funcionalidades já criadas mas que ainda não foram publicadas (depois será mesclada a branch main)
- **feat**: prefixo das branches usadas para desenvolver cada funcionalidade, sempre criadas a partir da develop. Depois de criada a funcionalidade, a branch é mesclada com a develop
- **fix**: prefixo das branches que serão criadas para resolver bugs encontrados na develop, que depois serão mescladas na develop
- **hotfix**:  prefixo das branch criada a partir da main para realizar correções imediatas encontradas no sistema em produção, sendio mesclada com a main e develop. Idealmente, a cada hotfix é criada uma tag com a nova versão do projeto
- **homolog**: branch para realização de testes

**Comment by ThHenrique** [comment]
@GabrielCamargoL @gioliveirass @JoaoM-py  - Fluxo de branches
